[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF7A29"
backgroundColor = "#0B0B0F"
secondaryBackgroundColor = "#15151C"
textColor = "#FFFFFF"
font = "sans serif"
